# Generated by Django 2.2.4 on 2019-08-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190828_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='repassword',
        ),
    ]
